name: sofiqe
description: A new Flutter project.
publish_to: 'none'
version: 1.2.3+6

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  camera: ^0.9.4+16
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  file_saver: ^0.1.0
  firebase_auth: ^3.3.9
  flutter_screenutil: ^5.1.1
  firebase_core: ^1.4.0
  devicelocale: ^0.5.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.2
  geocoding: ^2.0.0
  get: ^4.3.8
  location: ^4.2.0
  intl: ^0.17.0
  email_validator: ^2.0.1
  image: ^3.0.2
  country_code_picker: ^2.0.2
  top_snackbar_flutter: ^1.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  http: ^0.13.3
  provider: ^6.0.2
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.9
  dotted_border: ^2.0.0+2
  share_plus: ^4.0.1
  flutter_typeahead: ^3.2.0
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_svg: ^1.0.3
  dotted_line: ^3.0.0
  flutter_isolate: ^2.0.0
  # carousel_slider: ^4.0.0
  # flutter_unity_widget: ^4.2.1
  flutter_rating_bar: ^4.0.0
  flutter_share: ^2.0.0
  flutter_math_fork: ^0.6.1
  logger: ^1.1.0
  webview_flutter: ^3.0.1



  # For information on the



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information we use dependency overides
# that's will help us to compile depercated packages

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/eye/
    - assets/images/hair/  
    - assets/icons/
    - assets/icons/add_to_cart_white/
    - assets/icons/share/
    - assets/icons/eyes/
    - assets/icons/lips/
    - assets/db/sofiqe_questionnaire_db.db
    - assets/db/sofiqe_answer_db.db
    - assets/json/
    - assets/svg/

  fonts:
    - family: SkarpaRegular
      fonts:
        - asset: assets/fonts/Skarpa_regular.ttf
    - family: Arial
      fonts:
        - asset: assets/fonts/Arial_regular.TTF
